### ISSUE TITLE
Using Espressif's AWS Account Error

### ISSUE THREAD

**Issue by cmm711** [espressif/esp-va-sdk#125]
Dear Sir,
I got a problem when opening the URL of Certificate Generation on using Espressif's AWS Account.
That  URL seems like 404 already. Please check.
Thanks.

**Comment by chiragatal** [comment]
The Certificate Generation URL seems to be working fine: https://espressif.github.io/esp-va-sdk/#/
Can you try again? Maybe try with a different network?

**Comment by cmm711** [comment]
Well, looks like it was not working on mainland China network.

It works fine when I change to HK network.

Thank you very much.

 

Best Regards.

说明: 说明: 说明: hswlogo5

陈铭铭 CMM

Mobile: +86-13798286987

Email  :  <mailto:cmm@hsunwealth.com> cmm@hsunwealth.com

Office <tel:+86>  Tel: +86-755-2373-2403

地址: 深圳市宝安区31区前进一路186号东方明珠商务大厦603室

 

发件人: Chirag Atal [mailto:notifications@github.com] 
发送时间: 2020年12月11日 13:02
收件人: espressif/esp-va-sdk
抄送: cmm711; Author
主题: Re: [espressif/esp-va-sdk] Using Espressif's AWS Account Error (#125)

 

The Certificate Generation URL seems to be working fine: https://espressif.github.io/esp-va-sdk/#/
Can you try again? Maybe try with a different network?
