### ISSUE TITLE
Cannot get past [alexa]: Waiting for authentication tokens.

### ISSUE THREAD

**Issue by SamMcCormick61** [espressif/esp-va-sdk#128]
Have tried 20-30 times on different phones android and apple.
Unable to get past the  [alexa]: Waiting for authentication tokens message. Lights remains blue
Android ESP Alexa App allows to provision every time.
Alexa remains offline.

Some times on rebooting if I press button 1 it allows to reset

here is a monitor log.

C:\Users\Sam\Documents\GitHub\esp-va-sdk\examples\amazon_aia>idf.py -pCOM4 monitor
Executing action: monitor
Running idf_monitor in directory c:\users\sam\documents\github\esp-va-sdk\examples\amazon_aia
Executing "C:\Users\Sam\.espressif\python_env\idf4.2_py3.9_env\Scripts\python.exe C:\Users\Sam\esp\esp-idf\tools/idf_monitor.py -p COM4 -b 115200 --toolchain-prefix xtensa-esp32-elf- c:\users\sam\documents\github\esp-va-sdk\examples\amazon_aia\build\aia.elf -m 'C:\Users\Sam\.espressif\python_env\idf4.2_py3.9_env\Scripts\python.exe' 'C:\Users\Sam\esp\esp-idf\tools\idf.py' '-pCOM4'"...
?[0;33m--- WARNING: GDB cannot open serial ports accessed as COMx?[0m
?[0;33m--- Using \\.\COM4 instead...?[0m
--- idf_monitor on \\.\COM4 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4
load:0x3fff0034,len:7084
load:0x40078000,len:13240
load:0x40080400,len:4568
0x40080400: _init at ??:?

entry 0x400806f4
I (29) boot: ESP-IDF v4.2-dirty 2nd stage bootloader
I (29) boot: compile time 00:12:12
I (29) boot: chip revision: 3
I (32) boot.esp32: SPI Speed      : 80MHz
I (37) boot.esp32: SPI Mode       : DIO
I (42) boot.esp32: SPI Flash Size : 16MB
I (46) boot: Enabling RNG early entropy source...
I (52) boot: Partition Table:
I (55) boot: ## Label            Usage          Type ST Offset   Length
I (63) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (70) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (77) boot:  2 fctry_aia        WiFi data        01 02 00010000 00006000
I (85) boot:  3 fctry            WiFi data        01 02 00016000 00006000
I (92) boot:  4 otadata          OTA data         01 00 0001c000 00002000
I (100) boot:  5 ota_0            OTA app          00 10 00020000 003f0000
I (107) boot:  6 ota_1            OTA app          00 11 00410000 003f0000
I (115) boot: End of partition table
I (119) esp_image: segment 0: paddr=0x00020020 vaddr=0x3f400020 size=0x1f9dac (2071980) map
I (793) esp_image: segment 1: paddr=0x00219dd4 vaddr=0x3ffbdb60 size=0x04540 ( 17728) load
I (800) esp_image: segment 2: paddr=0x0021e31c vaddr=0x40080000 size=0x00404 (  1028) load
0x40080000: _WindowOverflow4 at C:/Users/Sam/esp/esp-idf/components/freertos/xtensa/xtensa_vectors.S:1730

I (801) esp_image: segment 3: paddr=0x0021e728 vaddr=0x40080404 size=0x018f0 (  6384) load
I (812) esp_image: segment 4: paddr=0x00220020 vaddr=0x400d0020 size=0x11d300 (1168128) map
0x400d0020: _stext at ??:?

I (1193) esp_image: segment 5: paddr=0x0033d328 vaddr=0x40081cf4 size=0x17670 ( 95856) load
0x40081cf4: start_cpu0_default at C:/Users/Sam/esp/esp-idf/components/esp32/cpu_start.c:361

I (1243) boot: Loaded app from partition at offset 0x20000
I (1243) boot: Disabling RNG early entropy source...
I (1244) psram: This chip is ESP32-D0WD
I (1249) spiram: Found 64MBit SPI RAM device
I (1253) spiram: SPI RAM mode: flash 80m sram 80m
I (1259) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (1266) cpu_start: Pro cpu up.
I (1270) cpu_start: Application information:
I (1275) cpu_start: Project name:     aia
I (1279) cpu_start: App version:      1.0
I (1284) cpu_start: Compile time:     Feb  8 2021 00:11:59
I (1290) cpu_start: ELF file SHA256:  f7a29dee3afda8bb...
I (1296) cpu_start: ESP-IDF:          v4.2-dirty
I (1302) cpu_start: Starting app cpu, entry point is 0x40081e5c
0x40081e5c: call_start_cpu1 at C:/Users/Sam/esp/esp-idf/components/esp32/cpu_start.c:287

I (0) cpu_start: App cpu up.
I (1800) spiram: SPI SRAM memory test OK
I (1804) heap_init: Initializing. RAM available for dynamic allocation:
I (1804) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (1806) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (1813) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (1819) heap_init: At 3FFC81B8 len 00017E48 (95 KiB): DRAM
I (1825) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1832) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1838) heap_init: At 40099364 len 00006C9C (27 KiB): IRAM
I (1844) cpu_start: Pro cpu start user code
I (1849) spiram: Adding pool of 4037K of external SPI memory to heap allocator
I (1870) spi_flash: detected chip: gd
I (1871) spi_flash: flash io: dio
I (1871) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (1878) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (1888) [app_main]: ==== Voice Assistant SDK version: v1.2.2 ====
I (1938) wifi:wifi driver task: 3ffd6630, prio:23, stack:6656, core=0
I (1938) system_api: Base MAC address is not set
I (1938) system_api: read default base MAC address from EFUSE
I (1958) wifi:wifi firmware version: 1865b55
I (1958) wifi:wifi certification version: v7.0
I (1958) wifi:config NVS flash: enabled
I (1958) wifi:config nano formating: disabled
I (1958) wifi:Init data frame dynamic rx buffer num: 32
I (1968) wifi:Init management frame dynamic rx buffer num: 32
I (1968) wifi:Init management short buffer num: 32
I (1978) wifi:Init static tx buffer num: 32
I (1978) wifi:Init tx cache buffer num: 32
I (1978) wifi:Init static rx buffer size: 1600
I (1988) wifi:Init static rx buffer num: 10
I (1988) wifi:Init dynamic rx buffer num: 32
I (1998) wifi_init: rx ba win: 16
I (1998) wifi_init: tcpip mbox: 32
I (1998) wifi_init: udp mbox: 6
I (2008) wifi_init: tcp mbox: 12
I (2008) wifi_init: tcp tx win: 14360
I (2018) wifi_init: tcp rx win: 14360
I (2018) wifi_init: tcp mss: 1440
I (2018) wifi_init: WiFi/LWIP prefer SPIRAM
I (2028) [app_smart_home]: Registering command: smart-home
[app_smart_home]: *************** Light's Power turned ON ***************
[app_smart_home]: *************** Light's Brightness changed to 100 ***************
I (2048) wifi_prov_scheme_ble: BT memory released
I (2078) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3
I (2078) I2S: PLL_D2: Req RATE: 48000, real rate: 48076.000, BITS: 16, CLKM: 13, BCK: 8, MCLK: 12292917.167, SCLK: 1538432.000000, diva: 64, divb: 1
I (2588) gpio: GPIO[12]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (2888) gpio: GPIO[12]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (2898) [scli]: Initialising UART on port 0
I (2898) [diag_cli]: Registering command: up-time
I (2898) uart: queue free spaces: 8

I (2898) [diag_cli]: Registering command: mem-dump
I (2908) [diag_cli]: Registering command: task-dump
I (2908) [diag_cli]: Registering command: cpu-dump
I (2918) [diag_cli]: Registering command: sock-dump
I (2918) [diag_cli]: Registering command: heap-trace
I (2928) [va_diag_cli]: Registering command: nvs-get
I (2928) [va_diag_cli]: Registering command: nvs-set
I (2938) [va_diag_cli]: Registering command: nvs-erase
I (2948) [va_diag_cli]: Registering command: reboot
I (2948) [va_diag_cli]: Registering command: crash
I (2958) [wifi_cli]: Registering command: wifi-set
I (2958) [app-auth]: Registering command: sign-in
I (2968) [app-auth]: Registering command: sign-out
I (2968) [speaker]: Registering command: vol-up
I (2978) [speaker]: Registering command: vol-down
I (2978) [speaker]: Registering command: vol-set
I (2988) [va_nvs_utils]: No value set for: speaker_vol
I (2998) [speaker]: Using default volume
[speaker]: Volume changed to 80
I (3008) [va_nvs_utils]: No value set for: sor_tone
I (3008) [va_nvs_utils]: No value set for: eor_tone
I (3018) [audio_codec]: Starting mp3_decoder codec
I (3018) [va_nvs_utils]: No value set for: wifi_reset_bit
[app_prov]: Starting provisioning
>> I (3108) phy: phy_version: 4500, 0cd6843, Sep 17 2020, 15:37:07, 0, 0
I (3108) wifi:mode : sta (24:0a:c4:e6:d9:b4)
I (3108) BTDM_INIT: BT controller compile version [3723d5b]
I (3358) wifi_prov_mgr: Provisioning started with service name : ESP-Alexa-D9B4
I (3358) [app_prov]: Provisioning started
[app_prov]: Provisioning started with:
        service name: ESP-Alexa-D9B4
        service key:
        proof of possession (pop): abcd1234
I (3378) [prompt]: Processing request ===> Play
I (3378) [focus_manager]: Acquire channel: Prompt Prompt

[prompt]: On Focus: Foreground
I (3388) [prompt]: Processing request ===> Foreground
I (3388) [sys_playback]: Acquire
[audio_codec]: Starting audio codec mp3_decoder
I (3398) [focus_manager]: Now active channel: Prompt Prompt

I (3408) [prompt]: Processing request ===> Play
I (3408) [audio_codec]: Codec mp3_decoder Event Started
[basic_player]: Codec event: Codec Started
I (3418) MP3Decoder: Found ID3 tag, skipping 45 bytes
I (3428) MP3Decoder: MP3 sync operation...
I (3428) MP3Decoder: MP3 sync success
I (3438) [audio_codec]: Codec mp3_decoder Event Set Freq
[basic_player]: Codec event: Codec Set Frequency
I (3448) [basic_player]: Set Freq event: 24000, 1, 16
I (3458) [prompt]: Processing request ===> Pipeline Started
I (3468) MP3Decoder: Codec reader finished
I (3488) MP3Decoder: Done with last chunk
I (3488) MP3Decoder: Closed
I (3488) [audio_codec]: Codec mp3_decoder Event Stopped
[basic_player]: Codec event: Codec Stopped
I (3918) [prompt]: Processing request ===> Pipeline Stopped
[audio_codec]: Starting audio codec mp3_decoder
I (3918) [audio_codec]: Codec mp3_decoder Event Started
[basic_player]: Codec event: Codec Started
I (3928) MP3Decoder: Found ID3 tag, skipping 45 bytes
I (3938) MP3Decoder: MP3 sync operation...
I (3938) MP3Decoder: MP3 sync success
I (3948) [audio_codec]: Codec mp3_decoder Event Set Freq
[basic_player]: Codec event: Codec Set Frequency
I (3958) [basic_player]: Set Freq event: 24000, 1, 16
I (3958) [prompt]: Processing request ===> Pipeline Started
I (7188) MP3Decoder: Codec reader finished
I (7498) MP3Decoder: Done with last chunk
I (7498) MP3Decoder: Closed
I (7498) [audio_codec]: Codec mp3_decoder Event Stopped
[basic_player]: Codec event: Codec Stopped
I (8368) [prompt]: Processing request ===> Pipeline Stopped
I (8368) [focus_manager]: Release channel: Prompt Prompt
I (8368) [focus_manager]: Releasing Prompt
I (8368) [sys_playback]: Release
I (29028) [va_nvs_utils]: No value set for: clientId
I (29028) [va_nvs_utils]: No value set for: refreshToken
I (29028) [avs_config]: Received sign in status request - false
I (29028) [va_nvs_utils]: No value set for: clientId
I (29038) [va_nvs_utils]: No value set for: refreshToken
I (29038) [avs_config]: Sending status SignedOut
I (29048) [avs_config]: 08 05 7a 02 08 04
I (29358) [avs_config]: Received request for device details
I (29358) [avs_config]: code_verifier - abcd1234, code_challenge - 6c7nGrky_ehjM40Ivk3p3-OeoEm9r7NCzmWexUULaa4
I (29358) [avs_config]: version: 1, DSN: 240ac4e6d9b4, ProductID: esp_alexa_open
I (37668) [avs_config]: Received configuration parameters
I (37668) [va_nvs_utils]: No value set for: clientId
I (37668) [va_nvs_utils]: No value set for: refreshToken
[avs_config]: App Got: ANbcLcmzrZXjQDGnJJUY, amzn1.application-oa2-client.320d0c28204541e4a061b7aff8e7d1b9, amzn://com.espressif.provbleavs, abcd1234
[auth-delegate]: Auth delegate with comp app: ANbcLcmzrZXjQDGnJJUY, amzn1.application-oa2-client.320d0c28204541e4a061b7aff8e7d1b9, amzn://com.espressif.provbleavs, abcd1234
W (37698) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
W (37908) wifi:Error! Should use default active scan time parameter for WiFi scan when Bluetooth is enabled!!!!!!

W (39708) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
W (41708) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
W (43708) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
W (45708) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
W (47708) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
W (49708) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
W (51708) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
W (53708) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
W (55708) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
I (56278) [app_prov]: Received Wi-Fi credentials:
        SSID: xxxxxxx
        Password: xxxxxxxx
W (57708) wifi:Haven't to connect to a suitable AP now!
[auth-delegate]: Waiting for network connection: 0x300f
I (57998) wifi:new:<3,0>, old:<1,0>, ap:<255,255>, sta:<3,0>, prof:1
I (58498) wifi:state: init -> auth (b0)
I (58508) wifi:state: auth -> assoc (0)
I (58508) wifi:state: assoc -> run (10)
I (58528) wifi:connected with Jacob, aid = 3, channel 3, BW20, bssid = 9c:80:df:bc:e3:9d
I (58528) wifi:security: WPA2-PSK, phy: bgn, rssi: -40
I (58538) wifi:pm start, type: 1

I (58558) wifi:AP's beacon interval = 102400 us, DTIM period = 1
[auth-delegate]: Waiting for voice_assistant initialisation.
[app_wifi]: Connected with IP Address: 192.168.1.213
I (59928) esp_netif_handlers: sta ip: 192.168.1.213, mask: 255.255.255.0, gw: 192.168.1.254
I (59928) wifi_prov_mgr: STA Got IP
I (59938) [app_prov]: Provisioning successful
[auth-delegate]: Waiting for voice_assistant initialisation.
I (63538) wifi_prov_mgr: Provisioning stopped
I (63538) [app_prov]: Provisioning stopped
I (63538) wifi_prov_scheme_ble: BTDM memory released
I (63548) [va_nvs_utils]: No value set for: friendlyname
I (63548) [va_nvs_utils]: No value set for: udn
I (63558) SSDP: Network Interface List (1):
I (63558) SSDP: 1. wifi  : 192.168.1.213
[alexa]: Waiting for time to be updated
I (63568) SSDP:

I (63578) LSSDP: create SSDP socket 58
[auth-delegate]: Waiting for voice_assistant initialisation.
[auth-delegate]: Waiting for voice_assistant initialisation.
[alexa]: Done getting current time: 1612808751
I (66998) [tls_certification]: Done setting global CA store
I (66998) [va_nvs_utils]: No value set for: clientId
I (66998) [va_nvs_utils]: No value set for: refreshToken
I (67008) [alexa]: Checking for companion app based authentication...

[alexa]: Waiting for authentication tokens.
W (67608) httpd_uri: httpd_uri: URI '/rootDesc.xml' not found
W (67608) httpd_txrx: httpd_resp_send_err: 404 Not Found - This URI does not exist
W (67618) httpd_uri: httpd_uri: URI '/rootDesc.xml' not found
W (67618) httpd_txrx: httpd_resp_send_err: 404 Not Found - This URI does not exist

**Comment by chiragatal** [comment]
Hi @SamMcCormick61 ,
1. Could you check your esp-idf branch? I think you are using v4.2 but it should be v4.0.
2. Can you tell which Android phone you are using? Could you try installing the Amazon Shopping app, sign-in into that with your account and try provisioning with ESP Alexa app again?
3. Also, make sure you are not 'skipping' the sign-in part and that it is successful in the ESP Alexa app.

**Comment by SamMcCormick61** [comment]
Thanks,
I will clear everything down and get esp-idf 4.0

I used a Samsung Note 8
Amazon shopping was installed,
I also have the Alexa app for my other echo dot and devices
Yes I believe the app is showing success as it gets to the screen asking you to ask Alexa something

I have also ordered another board from Diki-key for comparison.

I post here if I am successful or not.

**Comment by SamMcCormick61** [comment]
It is now working.

I  assumed my existing installation of esp-idf would work. I have learnt  my lesson.

Thank you for your prompt reply.

Now to try with my account

Sam

**Comment by SamMcCormick61** [comment]
All fixed
