### ISSUE TITLE
How to register two or more devices?

### ISSUE THREAD

**Issue by mongonta0716** [espressif/esp-va-sdk#139]
Hi, 

I am using multiple M5Stack Core2 for AWS IoT. When I use the same email address in the following certificate issuing site, I get an error message and cannot register.

- Error Message
"Active credentials for this email and cloud combination already exist"
- URL
https://espressif.github.io/esp-va-sdk/#/

If I use the certificate I obtained before, it will not authenticate at the same time and will not work.

I want to use Alexa on multiple devices at the same time, how can I get a certificate?

Thank you.

**Comment by chiragatal** [comment]
We have limited one certificate per email ID. You can use another email ID to generate another set of certificates.

**Comment by mongonta0716** [comment]
I was able to get a certificate with a different email address and run it at the same time. Thank you.

However, is the specification wrong?

**Comment by chiragatal** [comment]
Which specification are you talking about?

**Comment by mongonta0716** [comment]
It should be possible to assign multiple certificates to the same email address.

Users should be able to assign multiple certificates to the same email address, so that if they have more devices, they have to add more email addresses, even though they only have one Amazon account.

**Comment by mongonta0716** [comment]
My problem has been solved, so I'll close this once.

Thank you.
