### ISSUE TITLE
No rule to make target building error 

### ISSUE THREAD

**Issue by NikhilPatale** [espressif/esp-va-sdk#140]
Hello,
While trying to replicate the building and compile steps, I am facing with the following error log.
Any kind of guidance or help regarding this issue would be highly appreciated.
![Screenshot from 2021-07-27 00-14-15](https://user-images.githubusercontent.com/76599933/127041867-576d1716-b19b-4417-8be4-d2b04824bf63.png)

**Comment by chiragatal** [comment]
In the export commands, replace the '/path/to/' with the actual path to the repository. example: `export IDF_PATH=~/esp-idf/`

**Comment by NikhilPatale** [comment]
Hello Chirag, 
Many thanks for guiding through the above error, however I am facing a new issue after that. Attaching the Screenshot below. 
![1](https://user-images.githubusercontent.com/76599933/127217920-f2aa10b7-5d78-407c-9e1b-8bb49c9ed567.png)
 
I have also Installed the extensa toolchain with the following version.
![2](https://user-images.githubusercontent.com/76599933/127218088-5eb6284e-c806-40d1-959a-ef6002ee0ca4.png)

**Comment by chiragatal** [comment]
1. What is your IDF branch?
2. Are the submodules updated in IDF?
3. `[ALEXA_BT=1]` is an optional argument and is supposed to be used without `[]`. Remove that for now.
