### ISSUE TITLE
Example with support for tunein?

### ISSUE THREAD

**Issue by arlaor** [espressif/esp-va-sdk#16]
Hi.
Hello, I am using the ESP32-Lyrat module, and I would like to know if there is any developed code or example that allows TUNEIN or VTuner to be used?

**Comment by avsheth** [comment]
@arlaor TuneIn is supported by the SDK, you do not need any specific changes in the app code for that. So you can use default application available and can start using Amazon music and/or TuneIn.
We haven't tested VTuner yet though.

**Comment by arlaor** [comment]
Hi @avsheth 
In this moment i have mount [lyrat_alexa](https://github.com/espressif/esp-avs-sdk/tree/master/examples/lyrat_alexa) example, but I could not connect using the espressif application to esp32-lyrat. Which example can I mount to my module to use tunein? i´m used android lineage 16.0 in mi samsung GTI-9192. in the application I do not get provision screen.
Which example has the greatest emphasis on using tunein in esp32-lyrat?

**Comment by avsheth** [comment]
@arlaor 
1. Please checkout this [link](https://www.youtube.com/watch?v=dTJGbwirTnU&feature=youtu.be) to help you get through provisioning. Let us know if you still face any issues. 
2. You can use lyrat_alexa or lyrat_alexa_sr to play TuneIn stations. As soon as your board is provisioned you can wake the device using 'Alexa' (if you are using lyart_alexa_sr application) or you can press Rec button on the board to start recording your query (For both apps. Alexa is not required to be spoken in this case). And ask 'Play <station name> on TuneIn".
3. Unfortunately SDK doesn't have any example application which can load/play personalised radio station links.

**Comment by arlaor** [comment]
Hi @avsheth 

I will perform tests with the shown in the video and I will be commenting. For what is shown in the video I have omitted to apply the [esp-idf-patches](https://github.com/espressif/esp-avs-sdk/tree/master/esp-idf-patches).
In the changelog v1.0b1r4 (Beta) - 2018-09-28, "Support for PLS playlist parser" is mentioned. Can this be done from the Lyrat_alexa example or separately?

**Comment by arlaor** [comment]
Hi @avsheth 
I tried to follow the instructions given in the video, but when applying the patch time 0:31 sec
patch -p1 esp-avs-sdk/esp-idf-patches/memset-i2s-dma-buffers-zero.patch (location for me), I get the message -bash: patch: the order was not found
and therefore I believe that it does not make any modification that includes the patch.
I'm using mingW32.exe in windows 7. Do you have any suggestions to apply the patch?
so far the result is the beginning of this topic

**Comment by avsheth** [comment]
Hi @arlaor
1. In the command above you've missed redirection operator after -p1, it should be patch -p1 < esp-avs-sdk/esp-idf-patches/memset-i2s-dma-buffers-zero.patch. Probably that is why you are getting the error
2. Regardless on mingw you'll have to install "patch" package using command "mingw-get install msys-patch" to apply patches. 
2. OR alternatively you can use command "git apply esp-avs-sdk/esp-idf-patches/memset-i2s-dma-buffers-zero.patch" if you don't want to install the package.

**Comment by arlaor** [comment]
Hi @avsheth avsheth 

This repetitive message is for internet connection slow velocity?
*
rst:0x10 (RTCWDT_RTC_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:6320
ho 0 tail 12 room 4
load:0x40078000,len:10096
load:0x40080000,len:6700
entry 0x4008034c
[0;32mI (31) boot: ESP-IDF v3.1.1-54-g87f810dca-dirty 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 23:16:29[0m
[0;32mI (33) boot: Enabling RNG early entropy source...[0m
[0;32mI (37) qio_mode: Enabling QIO for flash chip GD[0m
[0;32mI (42) boot: SPI Speed      : 80MHz[0m
[0;32mI (47) boot: SPI Mode       : QIO[0m
[0;32mI (51) boot: SPI Flash Size : 4MB[0m
[0;32mI (55) boot: Partition Table:[0m
[0;32mI (58) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (65) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (73) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (80) boot:  2 avs              WiFi data        01 02 00010000 00006000[0m
[0;32mI (88) boot:  3 factory          factory app      00 00 00020000 00300000[0m
[0;32mI (95) boot: End of partition table[0m
[0;32mI (100) esp_image: segment 0: paddr=0x00020020 vaddr=0x3f400020 size=0x146b6c (1338220) map[0m
[0;32mI (462) esp_image: segment 1: paddr=0x00166b94 vaddr=0x3ffb0000 size=0x050cc ( 20684) load[0m
[0;32mI (469) esp_image: segment 2: paddr=0x0016bc68 vaddr=0x3ffb50cc size=0x00000 (     0) load[0m
[0;32mI (469) esp_image: segment 3: paddr=0x0016bc70 vaddr=0x40080000 size=0x00400 (  1024) load[0m
[0;32mI (478) esp_image: segment 4: paddr=0x0016c078 vaddr=0x40080400 size=0x03f98 ( 16280) load[0m
[0;32mI (492) esp_image: segment 5: paddr=0x00170018 vaddr=0x400d0018 size=0xff0a8 (1044648) map[0m
[0;32mI (772) esp_image: segment 6: paddr=0x0026f0c8 vaddr=0x40084398 size=0x15e30 ( 89648) load[0m
[0;32mI (802) esp_image: segment 7: paddr=0x00284f00 vaddr=0x400c0000 size=0x00000 (     0) load[0m
[0;32mI (802) esp_image: segment 8: paddr=0x00284f08 vaddr=0x50000000 size=0x00000 (     0) load[0m
[0;32mI (824) boot: Loaded app from partition at offset 0x20000[0m
[0;32mI (824) boot: Disabling RNG early entropy source...[0m
[0;32mI (825) spiram: SPI RAM mode: flash 80m sram 80m[0m
[0;32mI (830) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (837) cpu_start: Pro cpu up.[0m
[0;32mI (841) cpu_start: Starting app cpu, entry point is 0x400814cc[0m
[0;32mI (0) cpu_start: App cpu up.[0m
[0;32mI (1347) spiram: SPI SRAM memory test OK[0m
[0;32mI (1347) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1348) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1354) heap_init: At 3FFBF358 len 00020CA8 (131 KiB): DRAM[0m
[0;32mI (1360) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
[0;32mI (1366) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1373) heap_init: At 4009A1C8 len 00005E38 (23 KiB): IRAM[0m
[0;32mI (1379) cpu_start: Pro cpu start user code[0m
[0;32mI (1384) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
[0;32mI (1392) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
[0;32mI (71) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (71) alexa: ==== Alexa SDK version: v1.0b1-172316 ====[0m
Registering command: mem-dump 
[0;32mI (121) scli: Initialising UART on port 0[0m
[0;32mI (121) uart: queue free spaces: 8[0m

>>Registering command: task-dump 
Registering command: nvs-get 
Registering command: nvs-set 
Registering command: nvs-erase 
Registering command: reboot 
Registering command: heap-trace 
I (141) wifi: wifi driver task: 3ffc6df4, prio:23, stack:3584, core=0
I (141) wifi: wifi firmware version: a063b8c
I (151) wifi: config NVS flash: disabled
I (151) wifi: config nano formating: disabled
[0;32mI (151) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (161) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (171) wifi: Init dynamic tx buffer num: 32
I (181) wifi: Init data frame dynamic rx buffer num: 32
I (181) wifi: Init management frame dynamic rx buffer num: 32
I (191) wifi: Init static tx buffer num: 32
I (191) wifi: Init static rx buffer size: 2212
I (201) wifi: Init static rx buffer num: 10
I (201) wifi: Init dynamic rx buffer num: 32
[0;32mI (201) conn_mgr: Initialization success[0m
[0;32mI (211) conn_mgr: Received event: 0[0m
[0;32mI (211) sm_sta: In station start[0m
[0;32mI (221) sm_sta: Connecting to SSID: DESPLAZADOS[0m
 [0;32mI (281) phy: phy_version: 4000, b6198fa, Sep  3 2018, 15:11:06, 0, 0[0m
I (281) wifi: mode : sta (80:7d:3a:e1:51:2c)
[0;32mI (281) conn_mgr: SYSTEM_EVENT_STA_START[0m
[0;32mI (281) conn_mgr: Received event: 128[0m
I (1251) wifi: n:8 1, o:1 0, ap:255 255, sta:8 1, prof:1
I (2001) wifi: state: init -> auth (b0)
W (2001) wifi: discard, ba not setup
W (2001) wifi: discard, ba not setup
W (2001) wifi: discard, ba not setup
W (2001) wifi: discard, ba not setup
I (2011) wifi: state: auth -> assoc (0)
I (2021) wifi: state: assoc -> run (10)
I (2231) wifi: connected with DESPLAZADOS, channel 8
I (2231) wifi: pm start, type: 1

[0;32mI (2231) conn_mgr: SYSTEM_EVENT_STA_CONNECTED[0m
[0;32mI (2231) conn_mgr: Received event: 128[0m
[0;32mI (2231) alexa: got station connected event[0m
[0;32mI (3141) event: sta ip: 192.168.1.215, mask: 255.255.255.0, gw: 192.168.1.1[0m
[0;32mI (3141) conn_mgr: SYSTEM_EVENT_STA_GOT_IP[0m
[0;32mI (3141) conn_mgr: got ip:192.168.1.215[0m
[0;32mI (3141) conn_mgr: Received event: 128[0m
[0;32mI (3151) alexa: got IPv4:192.168.1.215[0m
[0;32mI (3151) I2S: DMA Malloc info, datalen=blocksize=600, dma_buf_count=3[0m
[0;32mI (3161) I2S: DMA Malloc info, datalen=blocksize=600, dma_buf_count=3[0m
[0;32mI (3171) I2S: PLL_D2: Req RATE: 16000, real rate: 16025.000, BITS: 16, CLKM: 39, BCK: 8, MCLK: 4096000.000, SCLK: 512800.000000, diva: 64, divb: 4[0m
[0;32mI (3181) gpio: GPIO[22]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:0 [0m
[0;32mI (3191) gpio: GPIO[19]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:0 [0m
[0;32mI (3201) UI_LED: LED initialized[0m
[0;32mI (3201) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:1 [0m
[0;32mI (3211) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:3 [0m
[0;32mI (3221) gpio: GPIO[21]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;32mI (3251) dsp: Created I2S audio stream[0m
[0;32mI (3251) audio_stream: Starting i2s_reader stream[0m
Starting audio stream i2s_reader
[0;33mW (3251) I2S: I2S driver already installed[0m
.......................Init i2s stream...............
[0;32mI (3261) audio_stream: Stream i2s_reader Event Started[0m
[0;32mI (3261) dsp: Reader stream event 2[0m
speech_recognizer: Ignoring data in idle state
speech_recognizer: Ignoring data in idle state
speech_recognizer: Ignoring data in idle state
Stopping audio stream i2s_reader
speech_recognizer: Ignoring data in idle state
[0;32mI (3291) audio_stream: Stream i2s_reader Event Stopped[0m
[0;32mI (3291) dsp: Reader stream event 3[0m
Generated stopped event for stream i2s_reader
[0;32mI (3301) I2S: PLL_D2: Req RATE: 48000, real rate: 48076.000, BITS: 16, CLKM: 13, BCK: 8, MCLK: 12292917.167, SCLK: 1538432.000000, diva: 64, divb: 1[0m
[0;32mI (3321) [alexa]: Waiting for time to be updated[0m
W (3501) wifi: discard, ba not setup
[0;32mI (3561) [alexa]: Done getting current time: 1543470306[0m
[0;32mI (3571) [tls_certification]: Done setting global CA store[0m
[0;32mI (3571) audio_stream: Starting playback_writer stream[0m
Starting audio stream playback_writer
[0;32mI (3581) audio_stream: Stream playback_writer Event Started[0m
[0;32mI (3581) LYRAT_CB: Current mode is: 8[0m
[0;32mI (3591) [dialog]: Entering ALEXA_IDLE[0m
[0;32mI (3591) avs-nvs-util: No value set for: speaker_vol[0m
[0;32mI (3601) [speaker]: Using default volume[0m
[0;32mI (3601) LYRAT_CB: Volume changed to 40[0m
[0;32mI (3611) auth-delegate-config: Returning auth delegate subsequent auth configuration[0m
W (4011) wifi: discard, ba not setup
W (4141) wifi: discard, ba not setup
W (5031) wifi: discard, ba not setup
W (5141) wifi: discard, ba not setup
W (5341) wifi: discard, ba not setup
[0;32mI (5351) [auth-delegate]: Token will be refreshed after 3000 seconds[0m
[0;32mI (5411) [auth-delegate]: Authentication Done ![0m
[0;32mI (5481) audio_codec: Starting mp3 codec codec[0m
[0;32mI (5491) audio_codec: Starting mp3 codec codec[0m
[0;32mI (5501) audio_codec: Starting aac codec codec[0m
W (5551) wifi: discard, ba not setup
[0;32mI (5591) audio_stream: Starting http_reader stream[0m
[0;32mI (5601) audio_codec: Starting mp3 codec codec[0m
[0;32mI (5601) audio_stream: Starting http_reader stream[0m
[0;32mI (5601) avs-nvs-util: No value set for: alert_0_data[0m
[0;32mI (5601) avs-nvs-util: No value set for: alert_1_data[0m
[0;32mI (5611) avs-nvs-util: No value set for: alert_2_data[0m
[0;32mI (5621) avs-nvs-util: No value set for: alert_3_data[0m
[0;32mI (5621) [alerts_nvs]: Alerts loaded from NVS[0m
[0;32mI (5621) [endpoint_handler]: AVS endpoint: https://avs-alexa-na.amazon.com[0m
[0;32mI (5631) [http_transport]: Connecting to server: https://avs-alexa-na.amazon.com[0m
[0;32mI (5641) sh2lib: [sh2-connect] Setting default tls_cfg parameter for alpn_proto.[0m
W (5651) wifi: discard, ba not setup
W (5851) wifi: discard, ba not setup
W (6061) wifi: discard, ba not setup
W (6981) wifi: discard, ba not setup
[0;32mI (6991) [http_transport]: HTTP2 Connection done[0m
[0;32mI (6991) [http_stream]: [stream-new] 106200 spiram 1286912[0m
[0;32mI (6991) [http_stream]: stream GET /v20160207/directives sid:1[0m
W (7181) wifi: discard, ba not setup
W (7391) wifi: discard, ba not setup
[sid: 1] Response code: 200
[sid: 1] Response content type is multipart/related; boundary=------abcde123; type=application/json
Final boundary:------abcde123:
[0;32mI (7401) [http_transport]: AVS level connction has now been established[0m
[0;32mI (7411) [http_transport]: Enqueueing avs_tx_sent for post_connect_object[0m
[0;32mI (7411) [http_stream]: [stream-new] 105152 spiram 1281416[0m
[0;32mI (7421) [http_transport]: New stream event: {"context":[{"header":{"namespace":"AudioPlayer","name":"PlaybackState"},"payload":{"token":"","offsetInMilliseconds":0,"playerActivity":"IDLE"}},{"header":{"namespace":"SpeechSynthesizer","name":"SpeechState"},"payload":{"token":"","offsetInMilliseconds":0,"playerActivity":"FINISHED"}},{"header":{"namespace":"SpeechRecognizer","name":"RecognizerState"},"payload":{"wakeword":"ALEXA"}},{"header":{"namespace":"Speaker","name":"VolumeState"},"payload":{"volume":40,"muted":false}},{"header":{"namespace":"Alerts","name":"AlertsState"},"payload":{"allAlerts":[],"activeAlerts":[]}},{"header":{"namespace":"Notifications","name":"IndicatorState"},"payload":{"isEnabled":false,"isVisualIndicatorPersisted":false}},{"header":{"namespace":"AudioActivityTracker","name":"ActivityState"},"payload":{}}],"event":{"header":{"namespace":"System","name":"SynchronizeState","messageId":"4bae5328-17cd-48e6-8b89-30d19f2e463b"},"payload":{}}}[0m
[0;32mI (7511) [http_stream]: stream POST /v20160207/events sid:3[0m
W (7511) wifi: discard, ba not setup
W (7701) wifi: discard, ba not setup
W (7901) wifi: discard, ba not setup
W (8111) wifi: discard, ba not setup
[sid: 3] Response code: 204
[0;32mI (8111) [http_transport]: [sid 3] stream close[0m
[0;32mI (8111) [http_stream]: [stream-delete] 104628 spiram 1287328[0m
W (8211) wifi: discard, ba not setup
W (8311) wifi: discard, ba not setup
W (9541) wifi: discard, ba not setup
W (12101) wifi: discard, ba not setup
W (17121) wifi: discard, ba not setup
W (23161) wifi: discard, ba not setup
W (35141) wifi: discard, ba not setup
W (36061) wifi: discard, ba not setup
W (39651) wifi: discard, ba not setup
*

**Comment by avsheth** [comment]
Access Point

**Comment by arlaor** [comment]
My router is connected in bridge mode.

**Comment by avsheth** [comment]
Okay. I believe setting router in bridge mode shouldn't be an issue. Can you help me with some other setup related queries below:
1. Are you using any repeater ?
2. Can you tell me name of router manufacturer, is it from D-Link, TP-Link or some other? And if possible it's model number too

Also if you have or could arrange a router from some other manufacturer, can you check if you are seeing the same issue with that too?

**Comment by arlaor** [comment]
Hi @avsheth 
The main router is a huawei adsl HG8546M. To this I connect with a Xiaomi mini router in bridge mode. The Xiomi mini router has the PADAVAN firmware installed (modified and adapted version of openwrt).
Although my ESP32-LYRAT connects to alexa and I can interact with it, the message
W (xxxx) wifi: discard, ba not setup
is presented in most cases after restarting the LYRAT module or turning it off and on again
I'm sorry, currently I do not have another router to perform tests.

**Comment by avsheth** [comment]
would it be possible to directly connect the board to main router and see if the problem persists?
currently we do not have this setup hence couldn't cross check the issue.

**Comment by arlaor** [comment]
Hi @avsheth 
So far I have not been able to perform tests with the board connected directly to the router. I have to wait to do it.
Other question:
Esp-avs-sdk has support for the [aithinker module esp32-A1S](http://wiki.ai-thinker.com/esp32-audio-kit)  or are you planning to support this board?

**Comment by avsheth** [comment]
Hi @arlaor Unfortunately we do not support aithinker module in our SDK yet. However, you can make changes to app_lyrat_cb.c in lyrat or lyrat_sr app to make it work.
You might need to change i2s write calls in va_app_playback_data function to write to DAC of ESP32.

**Comment by avsheth** [comment]
Hi @arlaor 
There isn't any documentation for this as such. But we are in a process of restructuring SDK to make is easy for users add support for a custom board (maybe with custom codec and DSP). This should be available by mid next week. I'll let you know once it is in place.

**Comment by avsheth** [comment]
Hi @arlaor 
Support to add a custom board have been available for quite some time now. You may refer to it to add your own board. Closing this issue. If you face any issues, kindly open another one.
