### ISSUE TITLE
Microphone gain

### ISSUE THREAD

**Issue by robertoimai** [espressif/esp-va-sdk#21]
Is there a way to control mic gain?
The function zl38063_set_mic_gain does nothing.

**Comment by kewalmshah** [comment]
HI @robertoimai, The zl38063 codec configuration will be opened by end of this month.

**Comment by diimdeep** [comment]
is zl38063 configurable on this board at the moment?

**Comment by kewalmshah** [comment]
https://github.com/espressif/esp-va-sdk/tree/master/board_support_pkgs/lyratd_msc/esp_codec/zl38063/components/codec_zl38063

The implementation is opened up here.
