### ISSUE TITLE
Unable to play Amazon Music on Lyrat board

### ISSUE THREAD

**Issue by Dinesh-Ramakrishnan** [espressif/esp-va-sdk#37]
When I request Alexa to play Amazon Music on Lyrat board, I get the error message  " Amazon music is not enabled on this device" , where as TuneIn radio works fine. 

I am using example/lyrat application.
Is there any configuration I need to do in order to enable Amazon music support?

**Comment by avsheth** [comment]
Hi @Dinesh-Ramakrishnan 
In order to play Amazon music and Saavn, Amazon mandates that client ID and client secret should be whitelisted from them.
If you are looking to go to production please let us know so that we can help you with that.
