### ISSUE TITLE
DialogFlow - LyraT Custom Wake Word

### ISSUE THREAD

**Issue by tickbw** [espressif/esp-va-sdk#38]
Hey All - 

Great project, love the LryaT.  I am trying to make a DialogFlow solution, but am finding that the README forces me to use the REC button to engage a conversation.  I would like the use the Custom Wake word features of DialogFlow, but don't see that capability in the source quite yet.  Am I missing something, or is this functionality missing from the SDK?

**Comment by dhrishi** [comment]
@tickbw As of now, we do not support custom wake word in esp-va-sdk. Although, we do have a customizable wakeword engine that can be easily paired with our Dialogflow SDK. For more details, please get in touch with sales@espressif.com
