### ISSUE TITLE
New Android app link for 1.0.RC1

### ISSUE THREAD

**Issue by sensoryhealthsystems** [espressif/esp-va-sdk#42]
In README/changelog , it says "Provisioning and authentication of Alexa app is now carried out over BLE instead of SoftAP. Use the new Android app for the same."

Can you point to where the new Android app/source code if we have compile the apk ?

**Comment by vikramdattu** [comment]
Here is the link for the app:

https://play.google.com/store/apps/details?id=com.espressif.provbleavs

**Comment by kedars** [comment]
The documentation is also now updated. Closing this.
