### ISSUE TITLE
source code for android app for new prov?

### ISSUE THREAD

**Issue by kvbulusu** [espressif/esp-va-sdk#43]
Is this still the source code for the new Android app ? 
https://github.com/espressif/esp-idf-provisioning-android/tree/versions/avs ?

**Comment by anujdeshpande** [comment]
@kvbulusu The source code is yet to be pushed for the new app. It should show up in the repo that you mentioned in a day or two.

**Comment by anujdeshpande** [comment]
@kvbulusu https://github.com/espressif/esp-idf-provisioning-android/tree/versions/avs-ble
