### ISSUE TITLE
Changing Amazon ProductID

### ISSUE THREAD

**Issue by alexm-snx** [espressif/esp-va-sdk#45]
I'm trying to change the productID used by esp-va-sdk and/or esp-idf-provisioning-android/avs-ble.
Using this version of the esp-va-sdk seems to give a hardcoded "ESP AVS Open".
I was setting the "product_id" in the build.gradle of the Android app I built from the esp-idf-provisioning-android/avs source, but in the avs-ble version it didn't seem to take effect.

A string search for both only finds the string in the libalexa.a and not in any source file I could find.
So, is there a some CONFIG_xxx flag or other setting I need to change?
![Alexa_ESP_AVS_Open_productID](https://user-images.githubusercontent.com/50181795/58291409-47339600-7d8b-11e9-807a-0dd63ae29ab2.PNG)

**Comment by avsheth** [comment]
Hi @alexm-snx 
You can change the product_id from app_main.c
product_id is a member of alexa_config_t structure. So in app_main.c you can set va_cfg->product_id = "<your product id>".
Please make sure to set it before provisioning is started. I'd recommend setting it immediately after va_cfg->auth_delegate.type = auth_type_subsequent line in app_main.c
