### ISSUE TITLE
 Please specify audio board path via AUDIO_BOARD_PATH。

### ISSUE THREAD

**Issue by lin-zi-jun** [espressif/esp-va-sdk#52]
我想/esp/esp-va-sdk/examples/amazon_alexa中的demo,但是提示路径没指定，提示： Please specify audio board path via AUDIO_BOARD_PATH。我该怎么指定路径呢？
我的编译环境是： MINGW32

**Comment by mingderwang** [comment]
I found this https://github.com/espressif/esp-va-sdk#14-the-esp32-vaquita-dspg-development-board
