### ISSUE TITLE
Alexa BOOK

### ISSUE THREAD

**Issue by tcpipchip** [espressif/esp-va-sdk#59]
Looks that the LINK 
 https://github.com/espressif/esp-avs-sdk/tree/master/examples/lyrat_alexa is broken
I am wrting a book about alexa and i have a lyra to test and write about on book
When can i find a step by step to compile ?
Got the error
Makefile:10: *** Please specify audio board path via AUDIO_BOARD_PATH.  Stop.

**Comment by kedars** [comment]
The AUDIO_BOARD_PATH needs to be defined to point to the LyraT board directory. 

You can find details about the compilation step here: https://github.com/espressif/esp-va-sdk/blob/master/README-Getting-Started.md
