### ISSUE TITLE
Alexa Amazon

### ISSUE THREAD

**Issue by tcpipchip** [espressif/esp-va-sdk#60]
Thanks for help Kedar

I will compile the Amazon Alexa to ESP32. 

About my book, i have done the integration with WEB/APP + ALEXA + LAMBDA + AWS IOT + ESP32.

I can send today send **phrase** like, TURN ON THE LIGHT, TURN OFF THE LIGHT

Today i need to use the WEB and APP to talk with ALEXA, now i want to replace them by LyraT.

With LyraT SDK is possible to config it to send those **phrases** too and Alexa answer that and signals to Lambda ?

**Comment by tcpipchip** [comment]
wich crosstool-ng to use ?
git checkout esp-2019r1-rc2 ?

**Comment by tcpipchip** [comment]
Kedar, good morning!
Could you do a video or something else to splain step to step how to compile the Amazon example ?
I am getting these errors!
I already tried all the versions!
![image](https://user-images.githubusercontent.com/11488460/62965480-89450480-bddb-11e9-869c-da83fce7acd1.png)

![image](https://user-images.githubusercontent.com/11488460/62965456-7c281580-bddb-11e9-831c-779072cc41ca.png)

**Comment by tcpipchip** [comment]
Looks that is not a problem with Toolchain
But asio lib problem
![image](https://user-images.githubusercontent.com/11488460/62970124-28bac500-bde5-11e9-902a-1846ebc8ab8f.png)

**Comment by tcpipchip** [comment]
Only can save us in this first step :)

**Comment by ChiragAtal** [comment]
Hi @tcpipchip , try doing `git submodule update --init --recursive` in esp-idf after you have changed your branch.

**Comment by tcpipchip** [comment]
I did that but
![image](https://user-images.githubusercontent.com/11488460/63012105-03b76800-be60-11e9-9e1f-76a6cf1eb767.png)
![image](https://user-images.githubusercontent.com/11488460/63012172-2ba6cb80-be60-11e9-8142-e27ed97011e4.png)

**Comment by tcpipchip** [comment]
![image](https://user-images.githubusercontent.com/11488460/63044709-2b7cef00-bea5-11e9-990c-2664fc44958e.png)
This is a error that gave me! If i remove that line compiles 100%
Are you having that error too ?

**Comment by tcpipchip** [comment]
is that line important ? I guess that the ALEXA dont use BLE services!

**Comment by dhrishi** [comment]
Please follow https://github.com/espressif/esp-va-sdk/blob/master/README-Getting-Started.md to get started.

From the first screenshot you have posted: https://github.com/espressif/esp-va-sdk/issues/60#issuecomment-520942891

It says compiler version 8.2.0 is not supported, expected version is 5.2.0.

We support version 8.2.0 from version ESP-IDF 4.0 onwards (and the current master branch).  As `esp-va-sdk` uses IDF 3.2, you need to make sure that the correct version of toolchain is used. These compilation errors should be gone if you choose the right version. You may follow "Setup Toolchain" here: https://docs.espressif.com/projects/esp-idf/en/v3.2/

**Comment by tcpipchip** [comment]
Yes, 
I was following those steps
But how i create a toolchain version 8.2.0 ? or if you give a link to download should be good ! :)

**Comment by dhrishi** [comment]
You ned to use version 5.2.0 and not 8.2.0

https://docs.espressif.com/projects/esp-idf/en/v3.2/get-started/linux-setup.html?highlight=setup%20toolchain#toolchain-setup

Also, once that is done, make sure that the PATH variable is updated with the correct path of the toolchain. As I mentioned, please follow this: https://docs.espressif.com/projects/esp-idf/en/v3.2/

**Comment by tcpipchip** [comment]
Nice, compiled 100% @dhrishi 
Thank you so much!
Next step is to install the app and config the AMAZON example, right ? Or do you have some other suggestion ? I want to connect to my amazon/SKILL account use the AVS services!
Give suggestions / tips for the next step after burn the software!
Thank you so much!!!!!
![image](https://user-images.githubusercontent.com/11488460/63050542-c2e83f00-beb1-11e9-8f54-aedd136c926e.png)

**Comment by kedars** [comment]
Yes, please use the 'ESP Alexa' app from the PlayStore to configure your LyraT to your home Wi-Fi network and login with your Amazon account.

**Comment by tcpipchip** [comment]
Thank you!!!!!!!!!!!!

I had problems with VM to recognize the USB SERIAL to burn the bin on Lyrat

I wll burn on Windows

Can you confirm me the address of 3 bin files on flashtools ?
bootloader, partitions and alexa 

Thanks again team!

**Comment by tcpipchip** [comment]
![image](https://user-images.githubusercontent.com/11488460/63108345-ffbd4000-bf5c-11e9-8059-cba6d18c11a2.png)

**Comment by tcpipchip** [comment]
is this ?
![image](https://user-images.githubusercontent.com/11488460/63108464-4f037080-bf5d-11e9-8796-ca202f7c74c5.png)

**Comment by avsheth** [comment]
Yep. You can now try and provision the device using the app.

**Comment by tcpipchip** [comment]
Thanks!!!! Can you post in your alexa bin files in some repository ? If mine not works and would like with yours compiled and compare too the bin size!

**Comment by tcpipchip** [comment]
All is working friends :)

**Comment by kedars** [comment]
Great

**Comment by tcpipchip** [comment]
hi 
Can you refresh my memory ?

> 
> osboxes@osboxes:~/esp/esp-va-sdk/examples/amazon_alexa$ ls
> additional_components  partitions_4mb_flash.csv  README-Alexa.md
> main                   partitions.csv            sdkconfig.bt.defaults
> Makefile               partitions_mkspiffs.csv   sdkconfig.defaults
> osboxes@osboxes:~/esp/esp-va-sdk/examples/amazon_alexa$ make
> Makefile:10: *** Please specify audio board path via AUDIO_BOARD_PATH.  Stop.
> osboxes@osboxes:~/esp/esp-va-sdk/examples/amazon_alexa$ 

thanks!

**Comment by tcpipchip** [comment]
Sir, in the make menuconfig (ALEXA EXAMPLE) there is a ENDPOINT to a AWS IOT. Can you explain how works ? Is that the MQTT IOT of AMAZON (the THING), if yes, where i define the TOPIC ?

**Comment by tcpipchip** [comment]
Hi, do you know how to use the alexa example with AI-THINKER ESP32-A1S ?
