### ISSUE TITLE
Alexa Portuguese

### ISSUE THREAD

**Issue by tcpipchip** [espressif/esp-va-sdk#65]
Hi, 

Last week, Alexa was ported to speak in Portuguese!

do you know how can i enable this SDK to talk in Portuguese ?
I already implemented on AVS the portugueses intends and sentences!

Thanks!!!!

**Comment by avsheth** [comment]
Hi @tcpipchip 
Sorry for the delayed response.
We are in the process of releasing this feature where you can set the Alexa language from the companion app.
We will update the repo by the end of next week.

Thanks

**Comment by tcpipchip** [comment]
Do you mean the mobile APP, right ?
Must i modify or recompile too the SDK ?
this is the best news of the week! thank you so much!!!!!!!!!!!!!!!!!

**Comment by avsheth** [comment]
1. Yes. You would be able to change it from Espressif's companion app. (which will be released too along with the new SDK).
2. Unfortunately you will need to recompile the SDK to bring in this new feature.

You can still try this feature in the existing SDK via CLI. On the device console you can enter command `locale pt-BR` to converse in portuguese. Only caveat being the setting will be resetted when device is rebooted.

**Comment by tcpipchip** [comment]
Do you mean if i connect lyrat on uart i can type something on rxd and receive a answer ?

**Comment by avsheth** [comment]
Yes.
You can either run `make monitor` to get the console or you can use any serial terminal emulator (teraterm, hyperterminal on windows or minicom,picocom on Linux/mac) to access the device console.

**Comment by tcpipchip** [comment]
Wonderfull! When have it i will finish the book!!!!

**Comment by tcpipchip** [comment]
Hi! Any update to Portuguese option in  SDK ?
I can see that the Mobile APP has update!

**Comment by avsheth** [comment]
Hi @tcpipchip ,
I am afraid it might get delayed by a week more. In the meantime, did you get to try with the CLI option?

**Comment by tcpipchip** [comment]
@avsheth 
Thanks! All going well now! CLI locale pt-BR works fine!!!!!
If someone in Brazil is interested, i did the Alexa BOOK using the Lyrat to tests :)

**Comment by tcpipchip** [comment]
https://www.youtube.com/watch?v=rBbXBzWCDIg

**Comment by avsheth** [comment]
Hi @tcpipchip 
Latest release includes support for A2DP sink and changing Alexa's language via the iOS and Android companion app.

Thanks

**Comment by tcpipchip** [comment]
hi @avsheth 
Thank you so much!!!!
Book going well :)

**Comment by tcpipchip** [comment]
Hi,
I am back with the esp-va-sdk

**Comment by tcpipchip** [comment]
https://www.youtube.com/watch?v=nyVm7-5g9CQ
