### ISSUE TITLE
About "com.espressif.provbleavs"

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-va-sdk#73]
@kedars 
Hi,
We can't access Google App Store in our region, 
can you put the apk in the latest releases?
Or update "https://github.com/espressif/esp-idf-provisioning-android/tree/versions/avs-ble"
to the latest commit, and we can build our APP.
Thanks!

**Comment by khushbushah2302** [comment]
Hi @xiruilin ,

Sure. We will update it soon.

**Comment by xiruilin** [comment]
Thanks!

**Comment by kirkrudolph** [comment]
Can you please update the iOS page https://github.com/espressif/esp-idf-provisioning-ios/tree/versions/avs too?

Thanks.

**Comment by khushbushah2302** [comment]
Yes. Sure. We will also update iOS code soon.
