### ISSUE TITLE
esp32-lyratd-syna audio board support

### ISSUE THREAD

**Issue by jhpark555** [espressif/esp-va-sdk#84]
I bought synaptics dsp board ( esp32-lyratd-syna). How do I configure or find synaptics audio board ?

**Comment by avsheth** [comment]
Hi @jhpark555 
Could you please drop an email ?

**Comment by jhpark555** [comment]
Yes my email is jhpark555@gmail.com.
Thanks.

**Comment by RickChou** [comment]
Hi avsheth：
我也有同樣的問題，請問該如何解決呢??

Best Regards.

**Comment by avsheth** [comment]
Hi @RickChou Sorry about the late response. If you are looking to commercialise your product, you can drop an email to sales@espressif.com along with your product info and estimated volume.
