### ISSUE TITLE
esp-va-sdk  ota

### ISSUE THREAD

**Issue by DuHeLong** [espressif/esp-va-sdk#86]
Hi,
Excuse me: Does esp-va-sdk support OTA function? I found in esp-va-sdk that there is no complete code that can be directly used to support OTA. If I need to start HTTP OTA, do I refer to the routine in the DIF: simple_ota_example to implement it?

**Comment by avsheth** [comment]
You can re-use code in simple_ota_example to add OTA support to Alexa.

**Comment by DuHeLong** [comment]
Thanks.
