### ISSUE TITLE
AVS iot & Cell modem

### ISSUE THREAD

**Issue by prasenjit-roy** [espressif/esp-va-sdk#97]
How can we route the data traffic via cell modem (uart/spi) when wifi is not available ?

**Comment by avsheth** [comment]
This would actually require quite some modifications to change the mode of transport in the SDK.
If you are looking to develop a commercial product, could you please drop an email along with your company info?

**Comment by prasenjit-roy** [comment]
Where do I drop the email ?

**Comment by avsheth** [comment]
Please drop an email at sales@espressif.com along with your product info and estimated volume.
