### ISSUE TITLE
AVS iot & BT Classic Source

### ISSUE THREAD

**Issue by prasenjit-roy** [espressif/esp-va-sdk#98]
How to use external Bluetooth Speaker with Alexa

**Comment by vikramdattu** [comment]
Current version does not support BT-SOURCE functionality. Upcoming versions will support this.

Current version supports BT-SINK functionality however, i.e., using Alexa speaker to stream music from other media devices such as smart-phones.
You can use this by setting ALEXA_BT=1 on build command.
